### ISSUE TITLE
Unable to Eject after saving with 'Bigtree3D to Removable Drive'

### ISSUE THREAD

**Issue by hapklaar** [bigtreetech/Bigtree3DPluginSuit#12]
Whenever I use this plugin to save the gcode to file, I can't use the Eject function to close the drive access before removal. This works fine when I save to drive without the Bigtree3D plugin.

It looks like something plugin related is keeping the file open

![image](https://user-images.githubusercontent.com/7703320/117711108-1e547780-b1d3-11eb-9886-fe7c2a967291.png)

**Comment by Wombat37** [comment]
I concur - I see the same thing.

**Comment by bigtreetech** [comment]
Yes, I have found the problem, which is not caused by file occupation. I am working on the problem, and I will update the plug-in again and inform you after the problem is solved.

**Comment by discip** [comment]
@bigtreetech
Still same problem here.

Is there any update on this topic yet?

thanks in advance

**Comment by bigtreetech** [comment]
Sorry, guys; I fixed the problem in the last update, but I forgot to notify everyone, so you can use the new version instead.

**Comment by discip** [comment]
Oh thanks.
Will try this later and report accordingly.

**Comment by discip** [comment]
@bigtreetech
Good evening sir,
what new version you are referring to?
Because the latest commit of the master branch does still not work! 😩

**Comment by gitmacer** [comment]
> 
> 
> Sorry, guys; I fixed the problem in the last update, but I forgot to notify everyone, so you can use the new version instead.

I also can't find that updated version.

**Comment by discip** [comment]
@bigtreetech
Would be nice, if you could take a stand on the *'update'* you mentioned above.

thanks in advance
regards

**Comment by radek8** [comment]
@discip, try this, it works for me
[Bigtree3DPlugin.zip](https://github.com/bigtreetech/Bigtree3DPluginSuit/files/6873572/Bigtree3DPlugin.zip)

**Comment by discip** [comment]
@radek8
First of all: Thank you!
But unfortunately this does not work for me. 😩🤷‍♂️

kind regards

**Comment by Wombat37** [comment]
Doesn't work for me either under Cura 4.9.0.

**Comment by radek8** [comment]
I have Windows10 and Ultimaker Cura 4.9.1 and it works well.
The plugin also worked in older versions of Cura.
Did you copy the "Bigree3DPlugin" folder to the "plugins" folder?

**Comment by discip** [comment]
Yes I did.
Win 10
Cura 4.10.0

**Comment by Wombat37** [comment]
OK - it's working for me now. I think I must have been doing something wrong earlier.

Cura 4.9.0
Windows 10

**Comment by Hitamku** [comment]
> @discip, try this, it works for me
> [Bigtree3DPlugin.zip](https://github.com/bigtreetech/Bigtree3DPluginSuit/files/6873572/Bigtree3DPlugin.zip)

![Screenshot 2021-07-28 154018](https://user-images.githubusercontent.com/13373210/127292231-67faef25-8317-4b82-99ba-61e09d618fe5.jpg)

Do you know where the problem is? I'm using 4.10 when this happens

**Comment by Hitamku** [comment]
@radek8 

![Screenshot 2021-07-28 154018](https://user-images.githubusercontent.com/13373210/127292451-f91b7c1b-3207-45ba-a03a-9ed51c2414c6.jpg)

Do you know where the problem is? I'm using 4.10 when this happens

**Comment by discip** [comment]
@bigtreetech
Are there any updates available by now?
I even tried it while all plugins were disabled. Without any success!

**Comment by tttttim5** [comment]
Well @radek8 what did you actually change in the code than? Because I can't find the issue.

By the way, I was adjusting the code and if you would like to save the gcode as the remaining time between brackets instead of "[Bigtree]" followed by ".gcode", change the following line (with notepad++ for example) (line 358 but depends on version):

bigtree3dfile = os.path.splitext(gfile)[0]+"[Bigtree].gcode"

by

bigtree3dfile = os.path.splitext(gfile)[0]+"["+str(Application.getInstance().getPrintInformation().currentPrintTime.days)+"_"+str(Application.getInstance().getPrintInformation().currentPrintTime.hours)+"_"+str(Application.getInstance().getPrintInformation().currentPrintTime.minutes)+"].gcode"
